//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public enum GameMessagesToServer
{
//	None                = 0,
//	JoinRoom            = 1,
//	JoinHome            = 2,
//	LeaveRoom           = 3,
	
		None=0,
		// function for register socket.io
		JoinFishRoom=1,// dang ky mot slot(dung cho socket.io)
		SubscribeResult=2,// result subscribe from server socket.io
		UnSubscribe=3,// huy dang ky (dung cho socket.io)
		RoomReady=4,// Room have already to play, broadcast information room to all room's clients
		SycnReady=5,// sync ready (dung cho socket.io)
		CaptureLogic=6,// log event client to broadcast to room
		FinalResult =7,// sync final result
		Benckmark=8,// benck mark server
		PlayAuto=9,// play with AI
		ReConnect=10,// reconnect
		UpdateProperties=22,
		LeaveCurrentRoom=23,
		LeaveWaitingRoom=24,
		
		// logicGame
		FigureDown=101,
		FigureUp = 102,
		FigureMove = 103,
		Shot = 104,
		HitFish=105,
		UpgradeGun = 106,
		ChangeMoney = 107,
		ChangeLevel = 108,
		StopShot = 109,
		RecivePresent = 110
}

public enum ChatMessageToServer
{
		None                = 0,
		//chat
		ConnectChat 		= 100,
		ChatPrivate 		= 101,
		ChatPublic 			= 102,
		JoinChatRoom 		= 103,
		LeaveChatRoom 		= 104,
		JoinChatParty 		= 105,
		LeaveChatParty 		= 106,
		eventType 			= 107
}
public enum MessagesFromServer
{
	
		None                = 0,	

		//game message
		Connected           = 1,
//	SystemLog           = 2,
//	JoinedRoom          = 3,
//	JoinedHome  		= 4,
//	OtherJoinedRoom     = 5,
//	OtherMoveTo         = 6,
//	LeftRoom            = 7,
//	OtherLeftRoom      	= 8,

		SubscribeResult		= 2,
		RoomReady 			= 4, 
		SycnReady			= 5,
		ClientLogic			= 6,
		FinalResult			= 7,

		HasError            = 10,
		SysPosition			= 20,
		SysPositionIsFail	= 21,
		ChatPublic 			= 1000,

}


public enum RequestType
{
		Ping				= 0,
	
		Login               = 1,

		MyInformation=11,//get thong tin nguoi choi
		Rooms=12,//get price room - mode online
		JoinWaittingRoom=20,//user vào phong cho

	


		Ranking 			= 100,
		Mission				= 101,
	
		TestDB				= 1000,
}