//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using SocketIOClient;
using SocketIOClient.Messages;

using System.Collections;
using System.Collections.Generic;

//public class M_C_JoinPlay : M_C_Base
//{
//		public int roomType;
//		public string userName;
//	
//		public M_C_JoinPlay (int rtype, string rName)
//		{
//				type = (int)GameMessagesToServer.JoinFishRoom;
//				roomType = rtype;
//				userName = rName;
//		}
//}

public class M_C_JoinFishRoom : M_C_Base
{

		public int roomId;
		public string userName;
		public int position;//1- 2- 3
	
		public M_C_JoinFishRoom (int rId, string _username, int _position)
		{
				type = (int)GameMessagesToServer.JoinFishRoom;
				roomId = rId;
				userName = _username;
				position = _position;

		}
}


//public class M_C_JoinPlayAuto : M_C_Base
//{
//		public int roomType;
//		public string userName;
//	
//		public M_C_JoinPlayAuto (int rtype, string rName)
//		{
//				type = (int)GameMessagesToServer.PlayAuto;
//				roomType = rtype;
//				userName = rName;
//		}
//}

public class M_C_SycnReady : M_C_Base
{
		public string UID;
		public M_C_SycnReady (string clientID)
		{
				type = (int)GameMessagesToServer.SycnReady;
				UID = clientID;
		}
}





public class M_C_CaptureLogic : M_C_Base
{
		public string UID;
		public string listEvent;
		public int score;
		public M_C_CaptureLogic (string _sid, string _listevent, int _score)
		{
				type = (int)GameMessagesToServer.CaptureLogic;
				UID = _sid;
				listEvent = _listevent;
				score = _score;
		}
}
public class M_C_Chat : M_Chat_Base
{
		public string message;
		public int roomType;
		public string roomName;
		public M_C_Chat (int _roomType, string _roomName, string _message)
		{
				type = (int)ChatMessageToServer.ChatPublic;
				roomType = _roomType;
				roomName = _roomName;
				message = _message;
		}
}
public class M_C_JoinChatRoom : M_Chat_Base
{
		public int roomType;
		public string roomName;
		public M_C_JoinChatRoom (int _roomType, string _roomName)
		{
				type = (int)ChatMessageToServer.JoinChatRoom;
				roomType = _roomType;
				roomName = _roomName;
		}
}

public class M_C_UpdateProperties:M_C_Base
{
		public string uid;
		public float score;
		public float gold;
		public float diamond;

		public M_C_UpdateProperties (string _uid, float _score, float _gold, float _diamond)
		{
				type = (int)GameMessagesToServer.UpdateProperties;
				uid = _uid;
				score = _score;
				gold = _gold;
				diamond = _diamond;
		}
}

public class M_C_LeaveWaitingRoom:M_C_Base
{
		public string uid;
		public M_C_LeaveWaitingRoom (string _uid)
		{
				type = (int)GameMessagesToServer.LeaveWaitingRoom;
				uid = _uid;
		}
}

public class M_C_LeaveCurrentRoom:M_C_Base
{
		public string uid;
		public M_C_LeaveCurrentRoom (string _uid)
		{
				type = (int)GameMessagesToServer.LeaveCurrentRoom;
				uid = _uid;
		}
}
public class M_C_RecivePresent:M_C_Base
{
	public int id;
	public M_C_RecivePresent (int _id)
	{
		type = (int)GameMessagesToServer.RecivePresent;
		id = _id;
	}
}

//public class M_C_JoinRoom:M_C_Base
//{
//	public int room_id;
//	
//	public M_C_JoinRoom (int rid)
//	{
//		type = (int)GameMessagesToServer.JoinRoom;
//		room_id = rid;
//	}
//	
//}
//
//public class M_C_JoinHome:M_C_Base
//{
//	public string user_uid;
//	
//	public M_C_JoinHome (string id)
//	{
//		type = (int)GameMessagesToServer.JoinHome;
//		user_uid = id;
//	}	
//}
//
//public class M_C_LeaveRoom:M_C_Base
//{
//	public M_C_LeaveRoom ()
//	{
//		type = (int)GameMessagesToServer.LeaveRoom;
//	}
//}


//public class M_C_MoveTo:M_C_Base
//{
//	public PositionData pos;
//	public bool teleport;
//	
//	public M_C_MoveTo (Vector3 destPos, bool teleport)
//	{
//		type = (int)GameMessagesToServer.MoveTo;
//		this.pos = new PositionData(destPos);
//		this.teleport = teleport;
//	}
//}
 
//public class M_C_RegisterPush : M_C_Base
//{
//	public string token;
//	public string os;
//	public bool isAccept;
//	public M_C_RegisterPush(string token, string os, bool isAccept)
//	{
//		type = (int)GameMessagesToServer.RegisterPush;
//		this.token = token;
//		this.os = os;
//		this.isAccept = isAccept;
//	}
//}

