//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using SocketIOClient;
using System.Collections;
using System.Collections.Generic;



public class M_S_ChatPublic:M_S_Base
{
	public int channel;
	public string user;
	public string mess;
	public string clientid;
	public string uid;
	//public string time;
	public override void Process()
	{
	}
}
public class M_S_ChatPrivate:M_S_Base
{
	public string user;
	public string mess;
	//public string time;
	public string clientid;
	public string uid;
	public bool mychat;
	public override void Process()
	{
		Debug.Log("[Private]:" + clientid + "-" + user + " say " + mess + " my chat : "+mychat);
	}
}

public class M_S_EventType:M_S_Base
{
	public string id;
	public string clientid;
	public string uid;
	public string user;
	public override void Process()
	{
		Debug.LogWarning("chat action : "+ id);
	}
}

public class M_S_SystemMess:M_S_Base
{
	public string mess;
	public override void Process()
	{
		Debug.LogWarning("[M_S_SystemMess]:" + mess);
	}
}

public class M_S_GlobalMessage:M_S_Base
{
	public string message;
	public int num;
	//public string time;
	
	public override void Process()
	{
		Debug.LogError("server mess: "+message);
	}
}