//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using SocketIOClient;
using SocketIOClient.Messages;

using System.Collections;
using System.Collections.Generic;

public class M_C_JoinPlay : M_C_Base
{
	public int roomType;
	public string userName;
	
	public M_C_JoinPlay(int rtype, string rName)
	{
		type = (int)GameMessagesToServer.Subscribe;
		roomType = rtype;
		userName = rName;
	}
}

public class M_C_JoinPlayAuto : M_C_Base
{
	public int roomType;
	public string userName;
	
	public M_C_JoinPlayAuto(int rtype, string rName)
	{
		type = (int)GameMessagesToServer.PlayAuto;
		roomType = rtype;
		userName = rName;
	}
}

public class M_C_SycnReady : M_C_Base
{
	public string SID;
	public M_C_SycnReady(string clientID)
	{
		type = (int)GameMessagesToServer.SycnReady;
		SID = clientID;
	}
}

public class M_C_CaptureLogic : M_C_Base
{
	public string SID;
	public string listEvent;
	public int score;
	public M_C_CaptureLogic(string _sid, string _listevent, int _score)
	{
		type = (int)GameMessagesToServer.CaptureLogic;
		SID = _sid;
		listEvent = _listevent;
		score = _score;
	}
}

//public class M_C_JoinRoom:M_C_Base
//{
//	public int room_id;
//	
//	public M_C_JoinRoom (int rid)
//	{
//		type = (int)GameMessagesToServer.JoinRoom;
//		room_id = rid;
//	}
//	
//}
//
//public class M_C_JoinHome:M_C_Base
//{
//	public string user_uid;
//	
//	public M_C_JoinHome (string id)
//	{
//		type = (int)GameMessagesToServer.JoinHome;
//		user_uid = id;
//	}	
//}
//
//public class M_C_LeaveRoom:M_C_Base
//{
//	public M_C_LeaveRoom ()
//	{
//		type = (int)GameMessagesToServer.LeaveRoom;
//	}
//}


//public class M_C_MoveTo:M_C_Base
//{
//	public PositionData pos;
//	public bool teleport;
//	
//	public M_C_MoveTo (Vector3 destPos, bool teleport)
//	{
//		type = (int)GameMessagesToServer.MoveTo;
//		this.pos = new PositionData(destPos);
//		this.teleport = teleport;
//	}
//}
 
//public class M_C_RegisterPush : M_C_Base
//{
//	public string token;
//	public string os;
//	public bool isAccept;
//	public M_C_RegisterPush(string token, string os, bool isAccept)
//	{
//		type = (int)GameMessagesToServer.RegisterPush;
//		this.token = token;
//		this.os = os;
//		this.isAccept = isAccept;
//	}
//}

