//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;
using SocketIOClient;
using SocketIOClient.Messages;

public class MC_S_Login
{
	public int error_code;
    public bool is_init;
}

public class MC_S_Connected
{
	public string id;
}

public class MC_S_ResultTestFunc
{
    public int result_code;
    public string value;

}

public class MC_S_ResponseTestPackage
{
	public int data;
}