//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using SocketIOClient;
using SocketIOClient.Messages;

public abstract class M_Chat_Base
{
	public int type = (int)ChatMessageToServer.None;
	
	public void Send(FHClient client)
	{
		if(client != null && client.ChatClient != null)
		{			
			IMessage mess = new JSONMessage(this);
//			Debug.Log("send to chat:" + (ChatMessageToServer)type + "-" + mess.MessageText);
			client.ChatClient.Send(mess);
		}
	}
	
}

public abstract class M_C_Base
{
	public int type = (int)GameMessagesToServer.None;

	/// <summary>
	/// Send the specified client.
	/// </summary>
	/// <param name="client">Client.</param>
	public void Send(FHClient c)
	{
		if(c != null && c.GameClient != null)
		{
			
			IMessage mess = new JSONMessage(this);
			Debug.LogWarning("Send Message:" + (GameMessagesToServer)type + "-" + mess.MessageText);
			c.GameClient.Send(mess);
		}
	}

	/// <summary>
	/// Send the specified c, responseMess, responseType and callback.
	/// </summary>
	/// <param name="c">C.</param>
	/// <param name="responseMess">Response mess.</param>
	/// <param name="responseType">Response type.</param>
	/// <param name="callback">Callback.</param>
	public void Send(FHClient c, MessagesFromServer responseMess, Type responseType, Action<object> callback)
	{
		if(c != null && c.GameClient != null)
		{
			
			IMessage mess = new JSONMessage(this);
			//Debug.Log("send to game:" + (eGameMessagesToServer)type + "-" + mess.MessageText);
			c.RegisterHandlerWithCallback(responseMess, responseType, callback);
			c.GameClient.Send(mess);
		}
	}
}

public abstract class M_S_Base
{
	public abstract void Process();
}

