//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

public class RequestPing : BaseRequest
{
	
	public RequestPing ()
	{
		type = (int)RequestType.Ping;
	}
}
public class ResponsePing : BaseResponse
{
}